import { getServerSession } from "next-auth";
import { authOptions } from "@/app/(auth)/api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

import NavBar from "@/components/mainNav/NavBar";

export const metadata = {
    title: 'Admin DashBoard',
    description: 'Generated by create next app',
  }

export default async function ContractsLayout({children, params}){

   const data= await getServerSession(authOptions);
    
   if(!data?.user){
      redirect('/');
   }
    return(
       <>        
          {children}
       </>
    )
}